# Generated by Django 5.2.3 on 2025-06-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token_hash',
        ),
    ]
